sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t akhils619/dockertest -f Dockerfile.dev Dockerfile.dev

script:
  - docker run -e CI=true USERNAME/docker-react npm run test
