sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t akhils619/dockertest -f Dockerfile.dev .

script:
  - docker run -e CI=true akhils619/dockertest npm run test
